// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8exU29k6gDUfM_FPVS3uSp3THNtHvfY',
    appId: '1:135485023164:web:dcccdc2e0ebd1f5b4081b9',
    messagingSenderId: '135485023164',
    projectId: 'eraasoft-3dfea',
    authDomain: 'eraasoft-3dfea.firebaseapp.com',
    storageBucket: 'eraasoft-3dfea.appspot.com',
    measurementId: 'G-C8NRSM6YVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7nSes9Ooy95u1x7xoh47rSkkq3GCNo80',
    appId: '1:135485023164:android:bb7f10de729ddc664081b9',
    messagingSenderId: '135485023164',
    projectId: 'eraasoft-3dfea',
    storageBucket: 'eraasoft-3dfea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2AXwHGatQwF75niIr4iYIg9-o-JaJ1M',
    appId: '1:135485023164:ios:2b85b139cdfa78074081b9',
    messagingSenderId: '135485023164',
    projectId: 'eraasoft-3dfea',
    storageBucket: 'eraasoft-3dfea.appspot.com',
    iosClientId: '135485023164-cep7sbqrcun8eh71aprjihek1q4dq2pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.api',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY2AXwHGatQwF75niIr4iYIg9-o-JaJ1M',
    appId: '1:135485023164:ios:2b85b139cdfa78074081b9',
    messagingSenderId: '135485023164',
    projectId: 'eraasoft-3dfea',
    storageBucket: 'eraasoft-3dfea.appspot.com',
    iosClientId: '135485023164-cep7sbqrcun8eh71aprjihek1q4dq2pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.api',
  );
}
